const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  panel: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SolarPanel',
    required: true,
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  type: {
    type: String,
    required: true,
    enum: [
      'dust_detected',
      'overheating',
      'performance_issue',
      'energy_loss',
      'voltage_fluctuation',
      'connection_error',
      'maintenance_required',
      'weather_alert',
      'efficiency_drop',
    ],
  },
  severity: {
    type: String,
    required: true,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium',
  },
  title: {
    type: String,
    required: true,
  },
  message: {
    type: String,
    required: true,
  },
  description: {
    type: String,
  },
  metrics: {
    temperature: Number,
    voltage: Number,
    current: Number,
    efficiency: Number,
    threshold: Number,
    actualValue: Number,
  },
  recommendation: {
    type: String,
  },
  status: {
    type: String,
    enum: ['new', 'acknowledged', 'in_progress', 'resolved', 'dismissed'],
    default: 'new',
  },
  isRead: {
    type: Boolean,
    default: false,
  },
  acknowledgedAt: {
    type: Date,
  },
  acknowledgedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  resolvedAt: {
    type: Date,
  },
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  autoGenerated: {
    type: Boolean,
    default: true,
  },
}, {
  timestamps: true,
});

alertSchema.index({ user: 1, status: 1, createdAt: -1 });
alertSchema.index({ panel: 1, severity: 1 });

module.exports = mongoose.model('Alert', alertSchema);
